server:
  port: 8082  #服务端口号
eureka:
  client:
    serviceUrl: #注册中心的注册地址
      defaultZone: http://192.168.17.129:8090/eureka/
spring:
  application:
    name: yd-jd-client #服务名称--调用的时候根据名称来调用该服务的方法
